<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8" />

    <!--====== Title ======-->
    <title>Biography &#8211; Fr Peter Mary Rookey &#8211; Servite Friar</title>

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!--====== Favicon Icon ======-->

    <!-- CSS
    ============================================ -->
    <?php 
    include '../config.php';
    include '../includes/head-links.php';
?>

</head>

<body>
    <!--====== Header Start ======-->
    <?php include '../includes/header.php'; ?>
    <!--====== Header Ends ======-->
    <section class="about-area">
        <!-- <div class="page-banner-bg bg_cover" style="background-image: url(assets/images/background.jpg);"> -->
      <div class="container">
        <div class="section-content">
            <h2 class="blog-title">Biography</h2>
            <p>Peter Byron Rookey was born to Anthony and Johanna (McGarry) Rookey in Superior, Wisconsin on October 12,1916. He was given the baptismal name of Joseph. He was born one year ( to the day) before the great miracle of Fatima. October 12th in the United States is October 13th in Fatima, Portugal because of the time difference. On that day the archangel St. Michael appeared to the three shepherd children; Lucia, Jacinta, and Francisco, one year preceding the miracle.</p>
            <p>Peter’s father Anthony was born in the province of Ontario, Canada in 1870. Anthony’s father Daniel was also born in Ontario province and his mother Annorah O’Melia was from Ireland. She was reportedly an herbalist who invented herbal remedies to cure diseases such as breast cancer. It seems that gifts of healing ran in Fr. Peter’s lineage! The original family name was Routhier which is French. Anthony and his brothers Americanized it when moving to the U.S. in the 1890s. Fr. Peter’s mother Johanna was born in Stillwater, Minnesota in 1879 to James McGarry from Limmerick, Ireland and Mary Ann Byron from St. Louis, Missouri. Father used to joke that “He was three quarters Irish and taking vitamins for the rest”. As a side note, Fr. Peter’s grandfather Daniel was first cousin to the famous Canadian, Adolphe Basille Routhier. who wrote the original words in French for “Oh Canada”, the Canadian national anthem . Adolphe also became the Chief Justice of Quebec.</p>
            <p>Peter’s father Anthony owned a furniture moving company called Rookey Transfer. He could be seen all around town, driving his horse-drawn wagon until six in the evening. His two large dray horses could carry quite a load! Two of the sons, Chet and Robert ( father of Timothy Rookey) later took over the business.</p>
            <p>Anthony and Johanna were blessed with thirteen children, four daughters and nine sons. Peter was the ninth child. We always say “We’re glad she didn’t say eight was enough”. Willa Rose, born in Willow River, Minnesota, was the oldest. Then, following, in order: Chester, Harold, Gordon, Mary, Robert, Genevieve, Kathryn, Peter, Bernard, Dale, Earl Thomas, and Richard. The daughters in the family played with the Casey girls, nieces of Fr. Solanus Casey who is now a saint of the Catholic Church. Two of the Casey girls later became nuns. One of the Rookey daughters had an interesting story of a healing due to Father Peter’s gift. When Genevieve (Rookey) and Joe Stack’s son Mark was sixteen he had a malignant brain tumor and was in a last stage coma. Fr. Peter was called in to bless him and commented that he “had seen corpses that looked better than that”. Later on that evening Mark came out of the coma and was completely cured. He went on to raise a family and live a long, healthy successful life. This account has been written up in the book, “The Living Christ,” by Harold Fickett.</p>
            <p>Johanna was a strong willed woman. She managed to raise with discipline and love all thirteen children, and still have time to help her husband with the moving business in secretarial work. It was said she made an average of 13 loaves of bread a week. Johanna was a beautiful petite woman, and Anthony very distinguished looking, with black hair, and a black mustache the way it was worn in the early 1900’s. In their wedding photo, Johanna’s sister, Margaret O’Toole, was her bridesmaid. She became the mother of Christopher O’Toole who was ordained a priest and later served as General of the Holy Cross Order of the U.S. and Canada, and over Notre Dame University, from 1950-1962. Father Peter’s love for his mother was tremendous. In later years, when she was struck with cancer, Father remembered coming home every year when he was in Belgium, and blessing her. Each time she was on the verge of death, and his blessing revived her for another year. Johanna finally succumbed to cancer on October 11th, 1953. Fr. Peter had just been assigned to Rome and heard of her death on his 37th birthday,  October 12th. Fr. Peter was unable to attend his mother’s funeral which was conducted by his first cousin, Fr. O’Toole.</p>
            <p>When little “Byron” as he was affectionately called, was nine years old a defining moment in his life happened. On July 4th after the fireworks display in town, he and his younger brother Bun (Bernard) were walking down their neighborhood street near their home on Ogden Ave., not far from downtown Superior.</p>
            <p>Being the curious and fun-loving boys that they were, when they found a fire-cracker that looked half-used they picked it up. Byron took it in his hand, lit it with a match and blew on it a little to get it going. It exploded in his face, severely injuring his eyes. They went home at once and told their mother, who took him right away to the doctor who lived down the block. How sad Johanna must have been when the doctor told her that her son was blind and would never see again. But the resilient, strong Irish woman knew when her faith was being put to the test. “We’ll see about that” she said, and took him home. From that night on she resolved to gather the whole family together every night and pray the rosary, begging our all-merciful Father in Heaven to grant little Peter a miraculous cure. Six months to a year passed, with the family faithfully praying the rosary every night. Sometime during that period Peter made a promise to God. He promised that if God would give him his sight back he would become a priest and serve Him whole-heartedly every day of his life.</p>
            <p>Well, I think you know the end of the story. Little Peter Byron did regain his sight completely within a year and a half of the accident. He entered Hillside Seminary in Chicago at age 13, in 1930. He was ordained a priest of the Servite Order on May 17th, 1941 at Our Lady of Sorrows Basilica, on Jackson Blvd near downtown Chicago. It was at this time that he chose to take the middle name of Mary. He also took the vows of Poverty, Chastity, and Obedience. This humble man never kept anything for himself. On all his travels, anytime someone gave him a present– he would turn around and give it to someone else. He became famous for doing this. Whenever you were around Father Peter, you knew you’d be getting some special presents.</p>
            <p>Totally devoted to the Blessed Mother, and always going to her son Jesus Christ our Lord through her, he was seldom seen without a rosary in his hands. He was in a state of constant prayer, whether it be the rosary of the Seven Sorrows of Mary, the Dominican rosary, Adoration of the Blessed Sacrament, or praying his daily breviary in Latin ( oftentimes as it was observed while standing on his head– “to get the blood flowing” as he said). Let us heed the promise of Our Lady during her appearances in Kibeho, Rwanda that “praying the rosary of the Seven Sorrows will soften the hardest of hearts. This rosary is comprised of seven Hail Mary beads, between seven Our Father’s. Meditating on the mysteries of: the Prophecy of Simeon, the Flight into Egypt, the Loss of the Child Jesus in the Temple, Mary meets Jesus on the Way to the Cross, Mary stands at the Foot of the Cross, Jesus is taken down from the Cross and laid in the arms of his Blessed Mother, and Mary accompanies Jesus to the tomb to await his Glorious Resurrection. There is a very moving, beautiful CD, made by Donald and Carol Wickman from  England, called “Canticle of Love” in which the Seven Sorrows Rosary is prayed by Father Peter, interwoven with song and violin between each mystery.</p>

            <p>It is also interesting to note that Father Peter had a degree in Gregorian Chant, and could sing and play the organ and piano quite well. He often would play the piano and sing after healing Masses, to the great delight of all around. He especially loved playing the “Ave Maria”, “Battle Hymn of the Republic”, “When Irish Eyes are Smiling”, and “Oh Danny Boy”. Up until his late eighties he would climb steps two-by-two up to the choir loft at Our Lady of Sorrows and play the organ– by ear. At that advanced age, he would walk the streets of Chicago for hours, praying the rosary on the way. He had good hearing until his later years, when he needed a hearing aid. His other hobbies included tennis, reading religious books and doing 200 push-ups and sit-ups each day. He also spoke four languages fluently: English, Latin, Italian, and German. Several other languages he spoke partially.</p>

            <p>His life took another turn when in 1948 he was asked by his Servite Provincial, Fr. James Mary Keane, O.S.M. ( who wrote a beautiful meditation on the Via Matris) to travel with him and five others to Benburb, County Tyrone, in Northern Ireland to establish the Servite Order there. They were bequeathed the ancient Benburb Castle and its surrounding buildings in which they founded the new Servite Monastery. Fr. Peter lived there for five years. It was here that his healing gift was discovered. People began coming up to him after Mass asking him to bless them for various ailments. One who had gout in his feet, another for a painful knee, and so on. Well, the following Sunday, they came back and said, “Father when you blessed me I was healed”. Word spread. Soon there were so many people coming that they had to hold the services outdoors. Everyone wanted a glimpse of this healing priest. Like Jesus Christ, they wanted to touch his garment that they might be healed. It must be noted that Father Peter never ever gave any credit of the healings to himself. He always gave all the credit to Jesus Christ, all for the Glory of God. He knew who did the healing. He was only the instrument. And if anyone ever did not want a blessing, he never forced it on anyone. He’d humbly joke about being just a “rookie” priest, and liked to say, “Donkeys bray. I just pray.”</p>

            <p>Father Peter had a heart for people. He took time for people. He never turned anyone away. He listened, gave advice, and many times a word of knowledge or prophecy was given to help a person. He spent hours blessing people, hearing confessions, and he did it with great love and grace. He always had a joke up his sleeve. People would often double over with laughter at his surprising, original, witty, and wise jokes. He was never boring to be around. There was always a story he could tell.</p>

            <p>Supernatural gifts such as the scent of roses would often occur during the healing Masses. Father Peter quite often saw the face of Christ in the sacred host during the consecration and the face of the  Blessed Mother, too, on occasion. Sometimes others saw Jesus in the host as well. People smelled the scent of roses coming from Father’s robe as he walked by. There were many reports of bi-location as well, including 42 people who called his office one day, claiming to have blessed by him as he walked through the crowds at Our Lady of Knock shrine in Ireland the previous day, even though he was at his office in Illinois at the time.</p>

            <p>The central focus of Father Peter’s healing ministry was “forgiveness”. He always stressed: “Hate and be sick. Love and be well, at peace.” He said unforgiveness was a form of hatred, and that this could block the healing the person should receive. He believed that in order to be healed one must forgive and forgive completely from the heart, as Jesus our Lord commanded us to do. If we don’t forgive others, our Heavenly Father can’t forgive us our sins. When one holds unforgiveness in their hearts, healing cannot take place. The famous “Miracle Prayer” that he composed expresses this key need of forgiveness. When one prays the “Miracle Prayer” sincerely, meaning every word, something good will happen. You will experience Jesus, and He will change your life.  Here is the “Miracle Prayer”:

            <div class="poem">
            <p><em>“Lord Jesus, I come before you just as I am. I am sorry for my sins. I repent of my sins. Please forgive me. In your name,</p>
            <p>I forgive all others for what they have done against me. I renounce Satan, the evil spirits and all their works. I give you my</p>
            <p>entire self, Lord Jesus, now and forever. I invite you into my life Jesus. I accept you as my Lord, my God, and my Saviour.</p>
            <p>Please heal me, change me, strengthen me in body, soul, and spirit. Come Lord Jesus, cover me with your precious</p>
            <p>blood, and fill me with your Holy Spirit. I love you, Lord Jesus, I praise you Jesus, I thank you Jesus. I shall follow you
            <p>every day of my life. Mary my mother, Queen of peace, St. Peregrine the cancer saint, all you angels and saints, please</p>
            <p>come to my aid. Amen, and amen.”</em></p>
            </div>

            <p>Perhaps Father Peter’s longevity and good health attest to his practice of complete forgiveness. He lived to be almost 98 years old, drove a car into his 90’s, and still walked sometimes 2 hrs. a night ( until age 88). He fasted daily. He believed that fasting opened him up to the flow of the Holy Spirit, which worked so powerfully through him during the healing services. He also performed several exorcisms, and believed fasting was important in deliverance. Father Peter would  have only a “wee bit” of coffee in the morning in order to “get the grouch off” he said, and then for the rest of the day would hardly eat anything except maybe half a piece of crusty bread. He would eat a full dinner at night ( and liked his ice-cream for dessert) which was often late, following his healing services. So many ladies loved cooking for him in their homes after healing Masses, or he would enjoy going out to a restaurant with friends, oftentimes 10 or 12 people joining him at a long table. These dinners were the most enjoyable of occasions, and sometimes lasted 2 or 3 hours. You see, when Father was there, Jesus was always present, too.</p>

            <p>When blessing people with his crucifix, that contained relics of the various Servite Saints and others, he would make the sign of the cross “in which we conquer” on their foreheads, with blessed St. Peregrine ( known as the cancer saint) oil. A priest would follow close behind carrying the Blessed Sacrament. Often Father would have a word of knowledge for a person. Usually the person would fall backwards, trustingly, though, as the catchers would gently lay them down on the floor. Then the individual would “rest in the Spirit” for a while, until the healing would be completed. Countless healings occurred through Father’s touch, all in the name of our Lord Jesus Christ. Healings that took place including healings of cancer, AIDS, alcoholism, drug addiction, blindness, and deafness. The mute and the  lame were healed along with those who suffered from emotional or spiritual troubles and women unable to conceive and bear children.. Anything you can imagine. Sometimes they were instantaneous, sometimes they were gradual. If a person was not healed, Father Peter explained that this was because God had other plans for them; to show His glory through their sickness. Perhaps, he said a person would not be healed because only God knew that this might make the person proud and might cause them to fall away from Him if they were healed. That they would be closer to God because of their affliction.</p>

            <p>After his five years of service in Ireland, in 1953 he was elected Assistant General of the Servite Order in Rome and lived there until 1959. It was during this time in Rome that Father Peter wrote the book on St. Anthony Pucci, called “Shepherd of Souls”. He spent time in Viareggio, Italy, where Maria Valtorta, the Catholic mystic (also a Servite) who wrote the “Poem of the Man God” had lived. Fr. Peter cherished a fondness for the “Poem of the Man God”, read it devoutly throughout his life, and often referred to it in his homilies. This is where he did much of his research on St. Anthony Pucci, who was also from Viareggio. St. Anthony was the patron saint of the Second Vatican Council. While living in Rome he also liked to take the early 4:00 a.m. train to San Giovanni Rotundo to attend Masses celebrated by St. Padre Pio. He sometimes cleaned up the altar after Mass. He also went to confession with St. Padre Pio a couple of times, and got advice from him on how to become a better priest. He often recalled one time in particular, when Padre Pio pointed at him sternly, and in a gruff voice counseled him, “Remember, Father, Obedience– always, obedience!”  This was something that proved to be very important in Fr. Peter’s priesthood.</p>

            <p>In 1959 he was transferred to the University of Louvain in Belgium where he headed the Servite Catholic College there until 1962. This is the University where Venerable Fulton Sheen graduated from. Then from 1962-1967 he served as a parish priest at Maria Himmelfahrt Church ( Mary of the Assumption) in Dusseldorf, Germany. After that he was assigned to the Servites Ozark mission churches in Ironton, Missouri from 1967-1984. From 1984 until 2002 he resided in Chicago, where he was allowed to continue his healing ministry. He conducted healing Masses every first Saturday at Our Lady of Sorrows Basilica in Chicago. About a thousand people would attend these, filling the church to capacity. These were extremely joyous, Spirit-filled occasions with beautiful singing, praying the rosary ( sometimes led in different languages), confessions, and a healing service, with the laying on of hands, after the Mass. There was a social gathering downstairs after the Mass. People came from near and far for these first Saturday healing services. After that, every first Saturday he would be driven to Midway airport in Chicago by his friend Jean Trilla where he’d get on the plane to the St. Louis area to conduct another healing Mass that evening.</p>

            <p>In addition to the healing services, Father Peter started the International Compassion Ministry, located in the Chicago suburb of Olympia Fields. Several volunteers and one paid secretary offered their time and talent to spread the ministry through answering  phone calls with prayer requests from all over the world, and offering up daily Masses in the chapel, rosaries, Divine Mercy chaplets, adoration of the Blessed Sacrament for all the various intentions. A monthly newsletter was published and as many as 40,000 were sent out all over the world. These newsletters were full of testimonies of healings that people had written and sent in to the office. A few of these can be read on this website. The phenomenon of the “miracle of the sun” (as seen in Medjugorje) was often seen from the window of the chapel, during the 3 o’clock hour recitation of the Divine Mercy chaplet. This miracle was entirely different from the “Great Miracle of the Sun” which occurred at Fatima, Portugal on Oct. 13th, 1917. Sometimes the sun pulsated, danced, or changed colors as many people testify. It was a joyful occasion to visit the office of the International Compassion Ministry, to attend Mass there in the chapel with Fr. Peter and the volunteers. Dozens of different priests from around the world came to concelebrate Mass in his chapel. We witnessed him conversing on the phone with people, patiently listening to their problems, and offering his blessing. Many healings occurred directly over the phone. It is a fond memory to think of him sitting there at his desk, his eyes twinkling, full of strong faith, a faith that could move mountains. One interesting note is that he told us he decided to grow his beard, beginning in 1995, not because he wanted to, but because the “Lord had put it upon his heart to grow a beard like the Jewish people used to do when in mourning. He was to wear the beard out of mourning for the unborn children cruelly sacrificed to abortion– the great scourge of our time– and he promised to “Wear this beard until abortion is aborted!” He shouted this from the pulpit at his first Saturday healing Mass at Our Lady of Sorrows Basilica.</p>

            <p>Father Peter traveled throughout the United States and the world to offer his healing Masses. He always had a full schedule. It was not for the faint-hearted. He was beloved in Ireland, England, Scotland, Poland, Mexico, South Africa, Kenya, Australia, Tazmania, the Philippines, American Samoa, Bosnia-Herzegovina, and even Lapland where he celebrated one of the only Masses that has ever been said there in over 400 years! He made close to 30 pilgrimages to Medjugorje and many trips to the Holy Land. Tens of thousands of people attended the healing Masses in Poland when he went there in December of 2004, the very last healing Masses he ever held. In the Catholic shrine of Medjugorje two important miraculous healings took place; that of David Parkes and Heather Duncan. David Parkes, the well-known singer from Ireland, was cured of Crohn’s disease in 1990. He had been close to death. His once robust frame as a professional footballer ( as a soccer player is called in Ireland) he was down to less than 100 lbs. and was languishing. He also had lost his faith. His wife Anne begged him to go to Medjugorje on a pilgrimage. She managed to cajole him into it by promising a side trip to the great walled-city of Dubrovnik, where they had spent their honeymoon years before. Well, good thing for him that he went. While in Medjugorje, Father Peter gave a healing service in the cemetery. He often held them, strangely enough, in the “dead center of town” as he put it. David reluctantly agreed to be blessed by the holy friar. He rested in the Spirit for 20 minutes and when he woke up was entirely healed. Today he sings only for God, and leads many pilgrimages to Medjugorje every year. David also shares his testimony of healing all around the globe. He sang the Schubert “Ave Maria” at Father Peter’s funeral. His CD’s can be ordered on E-Bay and Amazon.</p>

            <p>Heather Duncan was also the recipient of a miracle. She was a nurse living in Aberdeen, Scotland. One day she was lifting a patient that was too heavy, and the patient accidentally fell on her. Her spine was completely crushed, and she could no longer walk. She had to wear a steel harness on her torso. Months turned into years, and most of her time was spent in bed because she had so much pain. She had several operations, with no improvement. She came to believe that she was not supposed to be healed. She felt that the Lord had given her an Apostolate of Suffering, and that she was thankful she could suffer for the salvation of souls. Finally, she was taken to Medjugorje in 1990 by a friend. She was blessed by Father Peter Mary Rookey in the cemetery. He said to her, “Do you believe that Jesus can heal you?” She answered, “Yes, I do believe that Jesus can heal me, but I don’t think He wants to”. She grasped his crucifix with the relics in it, praying deeply in her heart. Then he said, “Silver or gold I have not to give you, but in the name of Jesus Christ, stand up and walk”. So she did. That smiling girl went home mystifying the doctors, and lived a long, happy life. She never had any more back pain. The second miracle was that later x-rays showed she should not have been able to walk, because her spine was still badly out of place. Both Heather Duncans’ and David Parkes’ miracles have been documented. Many other such stories can be read in the newspaper articles and viewed in the videos on our website. Fr. Peter gave many television interviews on talk shows in Ireland and the U.S. There were many radio broadcasts that featured him, and he was interviewed extensively by Margaret Trosclair, who headed Mary’s Helpers, based in New Orleans The documentary video “The Healing Priest” was made by Mary’s Helpers right around the year 1989. Also, a video was made of his trip to the Holy Land in 2010 with Chuck Neff from Relevant Radio and singer-songwriter Annie Karto, featuring her song, “Pilgrimage of Love”.</p>

            <p>He met many remarkable people, including St. Padre Pio, Maria Esperanza, St. Mother Teresa of Calcutta, stigmatist and mystic Therese Neumann, Carmelite Sister Celine Martin ( St. Therese of Liseaux’s last living sister), Pope Pius XII, and St. Pope John Paul II to name just a few. He celebrated Mass with the Archbishop of Nairobi, Kenya for Mother Teresa, her sisters, and novices in Nairobi, Kenya in 1995. He was close friends for decades with entertainer Bob Hope, and his wife Dolores Hope. He celebrated Holy Mass for Dolores in her home in Toluca Lake, California for her 100th birthday in 2009 along with two Cardinals. Bob Hope used to kid that he got his best jokes from Father Peter. Quite interestingly, Bob, a lifelong Protestant, became a Catholic in the last couple years of his life. His wife Dolores was a lifelong Catholic who went to Mass daily. In 1956 Dolores invited Father Peter to travel through Europe, visiting Catholic shrines with her children and actor John Wayne’s daughter. (John Wayne also became a Catholic, received into the Church on his deathbed). Fr. Peter made a side trip with Mrs. Hope to visit Padre Pio during that eventful 1956 pilgrimage. They met up with Bob Hope in Rome, and had a personal audience with Pope Pius XII. In October 1977 Bing Crosby and Mrs. Hope’s mother died on consecutive days. The Hopes asked Father Peter to accompany them to both funerals, which he did. At Bing Crosby’s wake, he sat next to Bob Hope and told him jokes to cheer him up.</p>

            <p>Several books have been written on the life of Father Peter Mary Rookey: “Man of Miracles” by Heather Parsons, “Healer of Souls” by Kathy Quasey, “Do You Believe that Jesus Can Heal You?” by Margaret Trosclair, and “Laborer of the Harvest In The Lord’s Vineyard” ( in Polish and English) by Barbara Wojtowicz. The healing ministry of Fr. Peter is prominently mentioned in many other books.</p>

            <p>On September 10th, 2014, Father Peter passed away unexpectedly, yet peacefully in his sleep with the rosary on his chest after eating a hearty meal in good spirits with his brother Servite priests</p>

            <p>It was no coincidence that his funeral was celebrated on the Feast of Our Lady of Sorrows, September 15th. He had been devoted to Our Sorrowful Mother his entire life. His wake at the Basilica lasted three days with thousands of people attending it.  Father Peter always told us “the more you think about others, the bigger you are and the more you think about yourself the smaller you are”. Oh, dear Father Peter how we miss your kind smile, your laughter, the way you loved us. We praise the Lord, now and forever, that you were such a great blessing to all of us!</p>

            <p><strong>>> Written by Anne Elizabeth Rookey, Father Peter’s Niece</strong></p>

            <p><strong>>> Edited by Timothy Peter Rookey, Father Peter’s Nephew</strong></p>
        <!-- </div> -->
      </div>
    </section>

<p>&nbsp;</p>
    <!--====== Footer Start ======-->

    <?php include '../includes/footer.php'; ?>
    <!--====== Footer Ends ======-->

    <!--====== BACK TOP TOP PART START ======-->

    <!-- <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a> -->

    <!--====== BACK TOP TOP PART ENDS ======-->

    <!--====== Jquery js ======-->
    <?php include '../includes/script-links.php'; ?>
</body>

</html>